### PR TITLE
Update to Elastic Stack 6.5.1

### PR DESCRIPTION
**Pull request by dadoonet**
Update to latest version.

### CODE REVIEW

**Comment by fxdgear** [comment]
Thanks for the patch. I'm going to leave this un-merged for the time being cause I noticed some errors when trying to do this earlier, I haven't had a chance to debug the whole issue but something changed in the way the keystores and initial passwords are handled.

**Comment by dadoonet** [comment]
For whatever reason I've been able to run it. I'm now trying to add beats monitoring but this is failing now.

**Comment by dadoonet** [comment]
@fxdgear I fixed some of the issues and added monitoring for beats.

Looks good on my end. Could you check?

image

**Comment by fxdgear** [comment]
@dadoonet thanks for the patch! :smile:

**Pull request merged**
