### PR TITLE
Patch which removed platinum following opening of X-Pack

### PR DESCRIPTION
**Pull request by deepybee**
`TAG=6.3.0 docker-compose up` launches Stack 6.3.0

### CODE REVIEW

**Comment by jarpy** [comment]
Thanks. There's another patch over in #44 now that updates all the images for the open X-Pack era.

**Comment by deepybee** [comment]
Cool, I'll close this PR and delete my branch then.

**Comment by jarpy** [comment]
Thanks for raising it reminding me to push my patch! I should have made it visible earlier. Apologies.

**Comment by jarpy** [comment]
Actually, my last patch was only half the job. Please pull master to make sure you also get 94d816d6db118cc4b8f04b94e1c2d949de12d9df.

**Pull request closed without merging**
